### ISSUE TITLE
# Cannot read property start of undefined 

### ISSUE THREAD

**Issue by subhadipghorui** [ivanstan/react-native-nmea-library#4]
Not working with react native. I am using expo to build react native app to log nmea data from my mobile GPS. I enable permision also.
This is my code:

###################################################
`import RNNmeaLibrary from "react-native-nmea-library";
import React, { Component } from "react";
import {
  StyleSheet,
  SafeAreaView,
  Text,
  DeviceEventEmitter,
} from "react-native";

export default class App extends Component {
  componentDidMount() {
    RNNmeaLibrary.start();

    DeviceEventEmitter.addListener("onNmeaReceive", (event) => {
      console.log(event);

      // will output:
      // {
      //   timestamp: 1543940192000,
      //   message: "$GLGSV,3,1,11,72,62,303,,73,59,028,,74,59,264,,71,54,180,*6"
      // }
    });
  }

  componentWillUnmount() {
    RNNmeaLibrary.stop();
  }
  render() {
    console.log("Start........ ");
    return (
      <SafeAreaView style={styles.container}>
        <Text>GPS</Text>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
`

> Can You provide me the Demo code to Check the app.

**Comment by subhadipghorui** [comment]
``
![image](https://user-images.githubusercontent.com/49529825/84777367-1f027f00-afff-11ea-81ee-b5b8a451ee21.png)

**Comment by ivanstan** [comment]
@subhadipghorui this happens because native plugin is not installed, meaning you cannot use native plugins with Expo. You will need to eject, install the react-native-nmea-library, link the plugin and compile the native application.

**Comment by subhadipghorui** [comment]
Thank You , for your reply.
can give me the steps how to link that with expo....or any blog to do that?......(I just started with React Native with expo last Month).
It will be very helpful.

**Comment by ivanstan** [comment]
Here are some tips on ejecting from Expo: 
https://medium.com/owhy/step-2-ejecting-from-create-react-native-app-a036c199addd
Make sure to commit before doing so, before once you eject you can go back only by reverting code.
Installing and linking library is explained in readme file https://github.com/ivanstan/react-native-nmea-library
